### ISSUE TITLE
How do I install this plug-in？

### ISSUE THREAD

**Issue by tom0gao** [cnhefang/image_picker_saver#1]
How do I install this plug-in？

**Comment by cnhefang** [comment]
https://pub.dartlang.org/packages/image_picker_saver

This plugin is still in developing and you can submit issuse if there is any isuese or send email to me,

**Comment by tom0gao** [comment]
@cnhefang Thank you. I'll help you with the test

**Comment by tom0gao** [comment]
@cnhefang Hello, No callback after save cannot sense success , Save failed on android device huawei P10, console print result is empty

**Comment by cnhefang** [comment]
Yes, I have removed return saved file path. You cat use try catch to confirm images saved or not.
I will try it on a HUAWEI device in hours.

**Comment by tom0gao** [comment]
@cnhefang Thank you, I will continue to pay attention to your project.

**Comment by cnhefang** [comment]
I have run it on HUAWEI Meta 9 Pro,EMUI 8.0.0, It works OK, Can you show me the debug logs what you said.

**Comment by tom0gao** [comment]
@cnhefang D/skia    (20591): --- SkImageDecoder::Factory returned null

**Comment by cnhefang** [comment]
I hava published a new version 0.0.2,and you can try it. And you can run the app on a emulator with offical Android system.
Last, What the url you download or what a image you want to save,can you put you code and image on comments?

**Comment by tom0gao** [comment]
@cnhefang    code snippet
 GlobalKey globalKey = new GlobalKey();

  RenderRepaintBoundary boundary =
    globalKey.currentContext.findRenderObject();
    ui.Image image = await boundary.toImage();
    ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.rawRgba);
    Uint8List pngBytes = byteData.buffer.asUint8List();

    ImagePickerUtils.saveImage('123.png', pngBytes,successCallback: (String imagePath){
      print(imagePath);
    });

new RepaintBoundary(
        key: globalKey,
        child:new Text('test'),
)

**Comment by cnhefang** [comment]
I have tried your code And saw the bug ,
You shoud use  ImageByteFormat.png to get byte array from a flutter image.
ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.png);

**Comment by tom0gao** [comment]
@cnhefang  Thank you, hope you can add file callback in the future

**Comment by cnhefang** [comment]
YES,It's in plan.

**Comment by cnhefang** [comment]
not add this feature
