### ISSUE TITLE
大佬小米系统保存不到相册看看是不是路径存错了，你写死的吗

### ISSUE THREAD

**Issue by chenxianqi** [cnhefang/image_picker_saver#16]
大佬小米保存不到相册看看是不是路径存错了，你写死的吗

**Comment by chenxianqi** [comment]
我看你保存的路径是pictures但是实际上小米系统不会检测该目录下的图片的

**Comment by chenxianqi** [comment]
小米相册默认把Pictures设为隐藏的相册，手动设置显示才能看到

**Comment by cnhefang** [comment]
Saving path in Android is using Environment.DIRECTORY_PICTURES

**Comment by chenxianqi** [comment]
Understand, it seems that there is no problem.
