### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by jintian93** [cnhefang/image_picker_saver#17]
It can not run on flutter projects using androidx

**Comment by atsuya** [comment]
It seems like ```master``` branch has the fix. You can pull from github repo by following [this instruction](https://www.dartlang.org/tools/pub/dependencies).

**Comment by lucasjinreal** [comment]
@atsuya  you mean load from git directly? Why not post to pub.dart.io?

**Comment by cnhefang** [comment]
I hava published a new version to pub.dartlang.org.
