### ISSUE TITLE
Some issue in example

### ISSUE THREAD

**Issue by CircleCurve** [cnhefang/image_picker_saver#2]
I have executed the code in example/lib/main.dart . And some error has appeared. 

![image](https://user-images.githubusercontent.com/8490834/45017563-77e76a00-b05a-11e8-8742-ffbf2d071630.png)

```dart
var filePath =await ImagePickerSaver.saveFile(fileData: pngBytes);
    var savedFile= File.fromUri(Uri.file(filePath));
    setState(() {
      _imageFile = Future<File>.sync(() => savedFile);
    });
```

I think it would be better to return file ? same with video ? It's my approach 
image_picker_saver.dart
```dart
static Future<File> saveFile({
    @required Uint8List fileData
  }) async {
    assert(fileData != null);

    final String path = await _channel.invokeMethod(
      'saveFile',
      <String, dynamic>{
        'fileData': fileData,
      },
    );
    return path == null ? null : new File(path) ; 
  }
```
main.dart
```dart
var filePath = await ImagePickerSaver.saveFile(fileData: response.bodyBytes);
    var savedFile= File.fromUri(Uri.file(filePath.path));
    setState(() {
      _imageFile = Future<File>.sync(() => savedFile);
    });
```

**Comment by cnhefang** [comment]
ImagePickerSaver.saveFile returns a String, so you can use filePath, but not  filePath.path.
Save video i have not tested.I will test that and add to sample.
And it's a good idea to change the return type to File, that will make the API style consistency.

**Comment by ameer-taghavi** [comment]
Video can not be saved
