### ISSUE TITLE
not able to save the file in ios13

### ISSUE THREAD

**Issue by adithya421** [cnhefang/image_picker_saver#29]
Dear Team,
I am using your plugin in one of my flutter application. its working fine in below ios13. However after upgrading to ios13 its giving below error. kindly suggest a solution to fix 

code:

final byteData = await image.toByteData(format: ImageByteFormat.png);
  Uint8List pngBytes = byteData.buffer.asUint8List();
    var filePath = await ImagePickerSaver.saveFile(fileData: pngBytes);

Flutter Version:
Flutter 1.9.1+hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2d2a1ffec9 (3 weeks ago) • 2019-09-06 18:39:49 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

• No issues found!

Xcode Log:
unner[32641:729850] save image successful
2019-09-26 09:37:58.007237+0300 Runner[32641:729850] [core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
2019-09-26 09:37:58.041160+0300 Runner[32641:729723] Success public.png {
    PHImageFileDataKey = {length = 1715209, bytes = 0x89504e47 0d0a1a0a 0000000d 49484452 ... 49454e44 ae426082 };
    PHImageFileOrientationKey = 0;
    PHImageFileUTIKey = "public.png";
    PHImageResultIsDegradedKey = 0;
    PHImageResultRequestIDKey = 1;
}
2019-09-26 09:37:58.041279+0300 Runner[32641:729723] Success PHImageFileURLKey (null)
2019-09-26 09:37:58.044804+0300 Runner[32641:729862] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Invalid argument(s)
#0      _StringBase.+ (dart:core-patch/string_patch.dart:263:57)
#1      ImagePickerSaver.saveFile (package:image_picker_saver/image_picker_saver.dart:85:34)
<asynchronous suspension>
#2      saveImageAndBytes (package:contract_followup_app/util/image_util.dart:38:43)
<asynchronous suspension>
#3      _BoardWdigetState._takeScreenshot (package:contract_followup_app/widgets/board_widget.dart:237:5)
#4      _BoardWdigetState._setupEvent.<anonymous closure> (package:contract_followup_app/widgets/board_widget.dart:110:9)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#14     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#15     _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)
#16     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#21     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#22     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#23     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#24     _rootRun (dart:async/zone.dart:1120:38)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by adithya421** [comment]
Any update on this issue 👍

**Comment by cnhefang** [comment]
Merged, Thank you.

**Comment by adithya421** [comment]
thank you its working fine. kindly release the package

**Comment by unclexiao** [comment]
I have the same problem,and I noticed this code:
```objective-c
            NSLog(@"save image successful ");
            PHFetchResult* assetResult = [PHAsset fetchAssetsWithLocalIdentifiers:@[localId] options:nil];
            PHAsset *asset = [assetResult firstObject];
            [[PHImageManager defaultManager] requestImageDataForAsset:asset options:nil resultHandler:^(NSData *imageData, NSString *dataUTI, UIImageOrientation orientation, NSDictionary *info) {
                NSLog(@"Success %@ %@",dataUTI,info);
                
                NSLog(@"Success PHImageFileURLKey %@  ", (NSString *)[info objectForKey:@"PHImageFileURLKey"]);
                fileName=((NSURL *)[info objectForKey:@"PHImageFileURLKey"]).absoluteString;
                _result(fileName);
            }];
```

It will print `Success PHImageFileURLKey (null)`.  

So actually saved to the phone, but can't get the file path.

**Comment by unclexiao** [comment]
Now that it’s fixed,right?  @cnhefang 

 is it planned to release a new version?
