### ISSUE TITLE
Save image file

### ISSUE THREAD

**Issue by VillzVic** [cnhefang/image_picker_saver#6]
![screenshot 2019-01-31 at 7 33 04 pm](https://user-images.githubusercontent.com/23703035/52076498-15ee4a80-258f-11e9-9dec-790a72dd0c68.png)

I get this response on my logs
![screenshot 2019-01-31 at 7 34 40 pm](https://user-images.githubusercontent.com/23703035/52076595-4b933380-258f-11e9-9338-9a4cfaee26e3.png)

Flutter version is v0.11.10

**Comment by gitgregoryjones** [comment]
I got this message before I did a 'flutter run -d all' in the terminal window   Camera functionality and some gallery functionality worked perfectly after this step.  There seems to be a bug on Android if you choose a gallery image from the download folder, sigh

**Comment by cnhefang** [comment]
> ![screenshot 2019-01-31 at 7 33 04 pm](https://user-images.githubusercontent.com/23703035/52076498-15ee4a80-258f-11e9-9dec-790a72dd0c68.png)
> 
> I get this response on my logs
> ![screenshot 2019-01-31 at 7 34 40 pm](https://user-images.githubusercontent.com/23703035/52076595-4b933380-258f-11e9-9338-9a4cfaee26e3.png)
> 
> Flutter version is v0.11.10

Can you post more details for you project, eg. iOS or android , versions, and even more code.
I guess you only run dart codes  of this  project, lost some codes  what iOS or android channel implements.

**Comment by cnhefang** [comment]
> I got this message before I did a 'flutter run -d all' in the terminal window Camera functionality and some gallery functionality worked perfectly after this step. There seems to be a bug on Android if you choose a gallery image from the download folder, sigh

I tested that, download a png image form web page and selected it. It works. You can create a new issue if you still have any problem.
