### ISSUE TITLE
请升级到AndroidX库

### ISSUE THREAD

**Issue by 39251474** [cnhefang/image_picker_saver#8]
大量插件开始支持AndroidX，项目正在迁移到AndroidX库

**Comment by yash365** [comment]
cannot understand can you write in english

**Comment by yash365** [comment]
how can i solve this issue : 
https://stackoverflow.com/questions/54784436/cannot-use-image-picker-saver-plugin-in-flutter

**Comment by cnhefang** [comment]
image_picker_saver hava upgraded to 0.3.0 and support Android X

**Comment by ghost** [comment]
I have also the same problem like @yash365
